http://localhost:8080/greeting?greeting=GoodBye

###
http://localhost:8080/datamodel/recipes
###
http://localhost:8080/recipes
Content-Type: application/json
Accept: application/json


###
http://localhost:8080/recipes/1
Content-Type: application/json
Accept: application/json


###
POST http://localhost:8080/recipes/create
Content-Type: application/json

{
"name":"Appeltaart"
}

###
http://localhost:8080/actuator/mappings

###

http://localhost:8080/actuator/health


###
# Should be off, now, but can be configured to work
http://localhost:8080/actuator/shutdown